### ISSUE TITLE
cmake build files bug?

### ISSUE THREAD

**Issue by mxttie** [luspi/photoqt-dev#32]
Hi,
congrats on this viewer project, I'm anxious to try it out!

First issue though: while trying to build on opensuse I noticed something's off with the exiv2 lib detection. Although the cmake configure detected exiv2, I still got a build error that it could not find its include file. So while I know I have to install the -devel package then, I guess it's a bug in the cmake script as it should have notified me about this before make?

so to reiterate, cmake said:
```
~/build/photoqt-dev/build> cmake ..

** Exiv2 enabled
** Graphicsmagick enabled

-- Configuring done
-- Generating done
-- Build files have been written to: /home/mattie/build/photoqt-dev/build
```
while make then said:
```
build/photoqt-dev/widgets/detailswidget.h:39:27: fatal error: exiv2/image.hpp: No such file or directory
 #include "exiv2/image.hpp"
                           ^
compilation terminated.
make[2]: *** [CMakeFiles/photoqt.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/photoqt.dir/all] Error 2
make: *** [all] Error 2
```
I'll try making an OBS package next :)

**Comment by luspi** [comment]
Hi @mxttie,

You're right, so far PhotoQt did not check for the exiv2 libs at all. I'll look into it. I already pushed something to GitHub, but it doesn't quite seem to work properly just yet...

Happy new year!

Lukas

**Comment by luspi** [comment]
Okay, it actually seems to work now... Thanks again, for pointing it out to me, I haven't thought of it beforehand!

Regards
Lukas

**Comment by mxttie** [comment]
cool, thx :) I've checked and it works as expected now. master build currently fails though ;)
i'm no expert but found this in the hugin project which appears to use pkg-config to detect libraries. in case you're interested: http://sourceforge.net/p/hugin/hugin/ci/default/tree/CMakeModules/FindExiv2.cmake
