### ISSUE TITLE
When using transition, transparent PNG incorrectly rendered

### ISSUE THREAD

**Issue by M4he** [luspi/photoqt-dev#39]
Good job on this software! This is easily becoming my standard image viewer!

I've noticed a reproducable problem though:
1. Enable image transition in advanced settings
2. Open up image within a folder that contains transparent PNG files
3. Navigate through the images until you reach a transparent PNG file
4. the background of the transparent PNG file will be the previously displayed image instead of transparent background

**Comment by luspi** [comment]
Hi @M4he 
Thanks for letting me know! The fix was actually very easy, I simply had to remove a few lines of old code, that was needed once but now only caused this problem and nothing else: b2b039552ae15f2074206dc0ecebd5c116e67e48
