### ISSUE TITLE
Not minimized in the system tray to esc

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-dev#42]
Sorry for bad English, I use google translate. I very like PhotoQt. When you press the esc PhotoQt not minimized in the system tray, but simply closes. Neither in the system tray or processes can not see it. Kubuntu 14.04

**Comment by luspi** [comment]
Hi @KOT040188 

Per default, PhotoQt does not minimise to system tray when it is closed. You need to enable this in the settings: In the first tab that opens, the third item from the top is "Hide to Tray Icon". Check the checkbox there and you're good to go...

**Comment by KOT040188** [comment]
Thank U =)
