### ISSUE TITLE
Style Sheet

### ISSUE THREAD

**Issue by iobzo** [luspi/photoqt-dev#45]
Hi, I like photoqt very much ,I am wondering why not put the css in a css file instead of in each c++ file, I think it's convenient  to change the style of photoqt by loading diffrent css. Maybe I am wrong?:) .Sorry for my bad English.
Thank you!

**Comment by luspi** [comment]
Hi @iobzo 
Thanks for the feedback! Seperating the CSS from the c++ code also came up in #34... It probably wont be happening for the Qt/QWidgets code here, but I am planning on doing exactly that (in a way) with the QML port that I'm currently working on [here](https://github.com/luspi/photoqt-qml-dev)...

**Comment by luspi** [comment]
PhotoQt is moving away from GitHub to GitLab ([more info](http://photoqt.org/news/1434375887)). This issue is duplicated here: https://gitlab.com/luspi/photoqt-legacy/issues
