### ISSUE TITLE
Stay small

### ISSUE THREAD

**Issue by xr09** [luspi/photoqt-dev#5]
Ok, right now everybody is asking for new features, do this, do that, add this option... but as one of the translators (not the most active lately ;) ) I can say the program is growing fast, this can be bad, you don't want to become yet another bloated image viewing software, we have tons of those, I like photo because does one thing really well, for editing I have gimp, for managing files I have dolphin, krusader, et al, don't bloat photo, the features you don't add are almost as important as the features you add, simplicity shines. (sorry for my mentality, but I read Rework by 37signals some time ago and get caught by the idea)

**Comment by luspi** [comment]
I think I close this one now... For further comments, you could re-surrect this issue on GitLab:
https://gitlab.com/luspi/photoqt-legacy/issues/46
